// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaEyFxTDf--G8dutkjuOhLJ5SHFhsh8O4',
    appId: '1:867715667838:web:31bc18875b2841695dc52f',
    messagingSenderId: '867715667838',
    projectId: 'ai-hackathon-project-1ada3',
    authDomain: 'ai-hackathon-project-1ada3.firebaseapp.com',
    storageBucket: 'ai-hackathon-project-1ada3.firebasestorage.app',
    measurementId: 'G-X0W3PXHGDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kFd2ixx_g_VncpPpkHFynERcr5S4umQ',
    appId: '1:867715667838:android:12762cda07d40d035dc52f',
    messagingSenderId: '867715667838',
    projectId: 'ai-hackathon-project-1ada3',
    storageBucket: 'ai-hackathon-project-1ada3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuptq4R8HBGrIQQWg0mRF045cPmEzM5Q4',
    appId: '1:867715667838:ios:4b1b9f150714fcc25dc52f',
    messagingSenderId: '867715667838',
    projectId: 'ai-hackathon-project-1ada3',
    storageBucket: 'ai-hackathon-project-1ada3.firebasestorage.app',
    iosBundleId: 'com.example.informalServiceAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuptq4R8HBGrIQQWg0mRF045cPmEzM5Q4',
    appId: '1:867715667838:ios:4b1b9f150714fcc25dc52f',
    messagingSenderId: '867715667838',
    projectId: 'ai-hackathon-project-1ada3',
    storageBucket: 'ai-hackathon-project-1ada3.firebasestorage.app',
    iosBundleId: 'com.example.informalServiceAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaEyFxTDf--G8dutkjuOhLJ5SHFhsh8O4',
    appId: '1:867715667838:web:a020d1c909353ccf5dc52f',
    messagingSenderId: '867715667838',
    projectId: 'ai-hackathon-project-1ada3',
    authDomain: 'ai-hackathon-project-1ada3.firebaseapp.com',
    storageBucket: 'ai-hackathon-project-1ada3.firebasestorage.app',
    measurementId: 'G-H0HHQSXCWY',
  );
}
